### ISSUE TITLE
Topgg 'Error handling request' issue

### ISSUE THREAD

**Issue by Splashtair** [Top-gg-Community/python-sdk#72]
This issue tracker is **ONLY** used for reporting bugs with __topggpy__. Feel free to share your suggestions in the #api channel in our [Discord server](https://discord.gg/EYHTgJX)!

For help with general Python issues, use [StackOverflow](https://stackoverflow.com), our [#development channel](https://discord.gg/EYHTgJX), or the [Python Discord server](https://discord.gg/python).

## Expected Behavior
Shouldn't post this error:
```py
Error handling request
Traceback (most recent call last):
File "/root/Senpai/venv/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 314, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
```

## Current Behavior
Posts this error:
```py
Error handling request
Traceback (most recent call last):
File "/root/Senpai/venv/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 314, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
```

## Development Environment
Python v3.8.10
Topggpy v1.4.0
OS is Linux

## Steps to Reproduce

1. Post your server count to top.gg 
2. Wait the X amount u set
3. Error should post when posting server count

## Context
My logs are spammed with this error and sometimes crashes it seems like

**Comment by shivaco** [comment]
Fun fact, no one figured out the cause (as far as I am aware, at least).

[This Reddit post](https://www.reddit.com/r/learnpython/comments/rptuq1/i_keep_bad_status_line_invalid_http_method/) gets into the causes of this error, although it is weird that a random request manages to reach web servers (yes, web servers) you, a Top.gg user, list in webhook URL settings. However, as a rule of thumb, such requests can be ignored.

**Comment by Esmeray6** [comment]
@null8626 Look into this, perhaps? Neither nori nor I figured out the reason (or, rather, never really bothered) and simply stuck with telling people to ignore it.

Could use an error handler that checks for this specific case.

**Comment by Esmeray6** [comment]
Alternatively, this issue can be closed.

**Comment by null8626** [comment]
I'll look into this later.

**Comment by Esmeray6** [comment]
Any update?

**Comment by Splashtair** [comment]
> Any update?

Honestly, I totally forgot about this issue. Not sure if you were talking to me, but I don't run that project anymore. Plus I am using topggpy with my current project and I am not facing any issues with it anymore.

**Comment by Esmeray6** [comment]
I assume the issue can be closed, then.

**Comment by null8626** [comment]
Huh, alright

**Comment by Splashtair** [comment]
> I assume the issue can be closed, then.

Yes it can be closed now. I will now close this issue.
